### ISSUE TITLE
狼人杀配置说明文档

### ISSUE THREAD

**Issue by kbkbsxwd** [geekan/MetaGPT#1142]
请问有狼人杀项目的相关配置说明文档吗？或者有相关交流群/社区也可以

**Comment by geekan** [comment]
You can ask questions directly, or through discord, or through the WeChat group (there are contact information above the discord-Chinese channel)

**Comment by kbkbsxwd** [comment]
<img width="1184" alt="1" src="https://github.com/geekan/MetaGPT/assets/95960312/2a8711aa-de92-41a0-b896-51073e7d12d5">
![image](https://github.com/geekan/MetaGPT/assets/95960312/b859b1e3-6b7e-40ac-a1f2-0e6808bca067)
![image](https://github.com/geekan/MetaGPT/assets/95960312/4adc684f-90f6-4b18-b9f5-667dd67bfb46)
![image](https://github.com/geekan/MetaGPT/assets/95960312/a6c1c5ac-ecfb-4903-9278-4f6f03b60f36)
请问这个问题我该如何解决？

**Comment by GreBai** [comment]
这是网络的问题，如果你想访问openai的api服务，需要添加代理
![image](https://github.com/geekan/MetaGPT/assets/115777999/7e3ff259-caf1-478d-b768-37aad0b04117)
lei类似于这样

**Comment by voidking** [comment]
这个问题确实是 GreBai 说的网络问题，可以参照他给的方法进行处理，也可以把base url改为openai api专用代理，比如 
```yaml
llm:
  api_type: 'openai' # or azure / ollama / open_llm etc. Check LLMType for more options
  model: 'gpt-4-turbo-preview' # or gpt-3.5-turbo-1106 / gpt-4-1106-preview
  base_url: 'https://render.openai-forward.com/v1' # or forward url / other llm url
  api_key: 'YOUR_API_KEY'
  # proxy: 'YOUR_LLM_PROXY_IF_NEEDED' # Optional. If you want to use a proxy, set it here.
  # pricing_plan: 'YOUR_PRICING_PLAN' # Optional. If your pricing plan uses a different name than the `model`.
```
