### ISSUE TITLE
how to support kimi?

### ISSUE THREAD

**Issue by victor-u** [geekan/MetaGPT#1151]
https://platform.moonshot.cn/docs/api-reference#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B

```
llm:
  api_type: ""  # or azure / ollama / open_llm etc. Check LLMType for more options
  model: "moonshot-v1-8k"  # or gpt-3.5-turbo-1106 / gpt-4-1106-preview
  base_url: "https://api.moonshot.cn/v1"  # or forward url / other llm url
  api_key: "sk-xxxx"
```

**Comment by geekan** [comment]
https://docs.deepwisdom.ai/main/en/guide/get_started/configuration.html

```
llm:
  api_type: 'moonshot'
  base_url: 'https://api.moonshot.cn/v1'
  api_key: 'YOUR_API_KEY'
  model: 'moonshot-v1-8k'
```
