### ISSUE TITLE
Possible to define multiple (local) LLM's in the config.yaml for different agents?

### ISSUE THREAD

**Issue by windowshopr** [geekan/MetaGPT#1266]
**Feature description**
Wondering if it's possible to define multiple `llm` configs to be used by different agents in the team? Or have the ability to override the config.yaml llm configs if one could pass the same parameters to an Agent class in code? For example, let's say I want to use the `llama2` or `llama3` model for a product owner role, and the `codellama:34b` model for the developer agents as it's (theoretically) better for training.

**Your Feature**
Could maybe do something like this:
```
llm:
  api_type: "openai" 
  model: "llama3"
  base_url: "http://127.0.0.1:11434/v1"
  api_key: "NA"
  utilizing_agents: ["product_manager", "project_manager"] # user defined, optional
llm:
  api_type: "openai"
  model: "codellama:34b"
  base_url: "http://127.0.0.1:11434/v1"
  api_key: "NA"
  utilizing_agents: ["engineer", "qa_engineer"] # user defined, optional
```

...or this (referencing the documentation):
```
async def startup(idea: str):
    company = Team()
    company.hire(
        [
            ProductManager(),
            Architect(),
            ProjectManager(),
            Engineer(api_type="openai", model: "codellama:34b", base_url: "http://127.0.0.1:11434/v1", api_key: "NA"), # overwrites the default config.yaml llm
        ]
    )
    company.invest(investment=3.0)
    company.run_project(idea=idea)

    await company.run(n_round=5)
```
