### ISSUE TITLE
第一次使用，能接入通义千问吗？文档没看到api示例

### ISSUE THREAD

**Issue by mbt1909432** [geekan/MetaGPT#1315]
第一次使用，能接入通义千问吗？文档没看到api示例
https://docs.deepwisdom.ai/main/zh/guide/get_started/configuration/llm_api_configuration.html#%E7%99%BE%E5%BA%A6-%E5%8D%83%E5%B8%86-api

**Comment by usamimeri** [comment]
文档里是有的，参考阿里云 灵积 DashScope API
```yaml
llm:
  api_type: 'dashscope'
  api_key: 'YOUR_API_KEY'
  model: 'YOUR_ENDPOINT_NAME like qwen-max'
```
