### ISSUE TITLE
ERROR    | metagpt.utils.mmdc_playwright:mermaid_to_file:118 - Page.goto: net::ERR_FILE_NOT_FOUND at file:///root/anaconda3/envs/metagpt/lib/python3.11/site-packages/metagpt/utils/index.html

### ISSUE THREAD

**Issue by happytravelingskysheep** [geekan/MetaGPT#1547]
**Bug description**
I installed playwright and its chrominum with the guidance and made configuration of mermaid. But it seems that the mermaid didn't work normally. 
```
ERROR    | metagpt.utils.mmdc_playwright:mermaid_to_file:118 - Page.goto: net::ERR_FILE_NOT_FOUND at file:///root/anaconda3/envs/metagpt/lib/python3.11/site-packages/metagpt/utils/index.html
Call log:
navigating to "file:///root/anaconda3/envs/metagpt/lib/python3.11/site-packages/metagpt/utils/index.html", waiting until "load"
```

**Bug solved method**
I think it may do with the configuration but the document of this part is not so clear. I don't know how to fill in the "path" if I'm using playwright and whether it is right to keep that stuff in default.

This is my configuration:
```yaml
llm:
  api_type: 'openai' # or azure / ollama / groq etc. Check LLMType for more options
  api_key: '[MY_API_KEY]' # MY_API_KEY
  model: 'yi-lightning' # or gpt-3.5-turbo
  base_url: 'https://api.lingyiwanwu.com/v1'  # or any forward url.
  # proxy: 'YOUR_LLM_PROXY_IF_NEEDED'  # Optional. If you want to use a proxy, set it here.
  # pricing_plan: 'YOUR_PRICING_PLAN' # Optional. If your pricing plan uses a different name than the `model`.

mermaid:
  engine: 'playwright' # nodejs/ink/playwright/pyppeteer
  # path: 'mmdc' # such as './node_modules/.bin/mmdc'
  # puppeteer_config: './config/puppeteer-config' # only for nodejs
  # pyppeteer_path: '/usr/bin/google-chrome-stable' # only for pyppeteer
```

This is your example:
```yaml
mermaid:
  engine: 'nodejs' # nodejs/ink/playwright/pyppeteer
  path: 'mmdc' # such as './node_modules/.bin/mmdc'
  puppeteer_config: './config/puppeteer-config' # only for nodejs
  pyppeteer_path: '/usr/bin/google-chrome-stable' # only for pyppeteer
```

**Environment information**
- LLM type and model name:
- System version: ubuntu 22.04
- Python version: 3.11
- MetaGPT version or branch:  0.8

- packages version:
- installation method: pip

**Screenshots or logs**
2024-10-29 16:22:16.900 | WARNING  | metagpt.utils.cost_manager:update_cost:49 - Model yi-lightning not found in TOKEN_COSTS.
2024-10-29 16:22:16.903 | INFO     | metagpt.utils.git_repository:rename_root:219 - Rename directory /root/workspace/cited_papaer_eval/workspace/20241029162137 to /root/workspace/cited_papaer_eval/workspace/scholar_cited_evaluation
2024-10-29 16:22:16.904 | INFO     | metagpt.utils.file_repository:save:57 - save to: /root/workspace/cited_papaer_eval/workspace/scholar_cited_evaluation/docs/prd/20241029162216.json
2024-10-29 16:22:17.435 | ERROR    | metagpt.utils.mmdc_playwright:mermaid_to_file:118 - Page.goto: net::ERR_FILE_NOT_FOUND at file:///root/anaconda3/envs/metagpt/lib/python3.11/site-packages/metagpt/utils/index.html
Call log:
navigating to "file:///root/anaconda3/envs/metagpt/lib/python3.11/site-packages/metagpt/utils/index.html", waiting until "load"
