### ISSUE TITLE
Run o1 with MetaGPT, cannot produce any output. 

### ISSUE THREAD

**Issue by hohoCode** [geekan/MetaGPT#1628]
**Bug description**
1. When running o1, with examples/build_customized_multi_agents.py, no output is shown in the terminal. But o1 is indeed being used and charged.
2. logs does have the o1 output as 'DEBUG', it is just not shown in the terminal
3. If switch to gpt4, everything is working.

**Environment information**
o1 and o1 mini both have the issue. No output in the terminal.

- System version: Linux
- MetaGPT version or branch: Latest metaGPT github repo installation as of today.

**Comment by shenchucheng** [comment]
Please update your configuration as follows:  

```yaml
llm:
  api_type: 'openai'
  api_key: 'sk-...'
  model: 'o1-mini'
  use_system_prompt: false
  stream: false
```  

Make sure `use_system_prompt` and `stream` are set to `false`.
