### ISSUE TITLE
access to deepseek

### ISSUE THREAD

**Issue by Dwendwen-Liu** [geekan/MetaGPT#1629]
want to access to deepseek!!!!

**Comment by shenchucheng** [comment]
```
llm:
  api_key: sk-xxxxxxxxxxxxxxxxxxxx
  api_type: openai
  base_url: https://api.deepseek.com/v1
  model: deepseek-chat  # deepseek-coder
```
See, https://api-docs.deepseek.com/.
