### ISSUE TITLE
依据AFLOW的readme执行报错，The optimization model 'gpt-3.5-turbo' was not found in the 'models' section of the configuration file.

### ISSUE THREAD

**Issue by Eyict** [geekan/MetaGPT#1656]
目前在config.config2.yaml下配置好了模型以及key,url等参数，仍报错执行报错，The optimization model 'gpt-3.5-turbo' was not found in the 'models' section of the configuration file.
之前并未用过metagpt中其他项目，请问是否在运行Aflow之前还需要别的前置准备？

**Comment by iorisa** [comment]
[README.md](https://github.com/didiforgithub/MetaGPT-AFLow/blob/main/examples/aflow/README.md#quick-start)中的描述有歧义：
> Configure LLM parameters in config/config2.yaml (see examples/aflow/config2.example.yaml for reference)
实际上要配的是`models`那里：
```yaml
llm:
  api_type: "openai"  # or azure / ollama / groq etc.
  base_url: "YOUR_BASE_URL"
  api_key: "YOUR_API_KEY"
  model: "gpt-4-turbo"  # or gpt-3.5-turbo
  proxy: "YOUR_PROXY"  # for LLM API requests
  # timeout: 600 # Optional. If set to 0, default value is 300.
  # Details: https://azure.microsoft.com/en-us/pricing/details/cognitive-services/openai-service/
  pricing_plan: "" # Optional. Use for Azure LLM when its model name is not the same as OpenAI's

......

models:
#  "YOUR_MODEL_NAME_1 or YOUR_API_TYPE_1": # model: "gpt-4-turbo"  # or "gpt-3.5-turbo"
#    api_type: "openai"  # or azure / ollama / groq etc.
#    base_url: "YOUR_BASE_URL"
#    api_key: "YOUR_API_KEY"
#    proxy: "YOUR_PROXY"  # for LLM API requests
#    # timeout: 600 # Optional. If set to 0, default value is 300.
#    # Details: https://azure.microsoft.com/en-us/pricing/details/cognitive-services/openai-service/
#    pricing_plan: "" # Optional. Use for Azure LLM when its model name is not the same as OpenAI's
#  "YOUR_MODEL_NAME_2 or YOUR_API_TYPE_2": # api_type: "openai"  # or azure / ollama / groq etc.
#    api_type: "openai"  # or azure / ollama / groq etc.
#    base_url: "YOUR_BASE_URL"
#    api_key: "YOUR_API_KEY"
#    proxy: "YOUR_PROXY"  # for LLM API requests
#    # timeout: 600 # Optional. If set to 0, default value is 300.
#    # Details: https://azure.microsoft.com/en-us/pricing/details/cognitive-services/openai-service/
#    pricing_plan: "" # Optional. Use for Azure LLM when its model name is not the same as OpenAI's

......

```

**Comment by Eyict** [comment]
![image](https://github.com/user-attachments/assets/a9da2c71-66be-4265-964c-307b9e987c16)
我修改了此处的config.yaml为
![image](https://github.com/user-attachments/assets/fb23922f-45d4-42f6-afbb-8abf694205af)，对于代码中，CONFIG_ROOT如果不修改指定的路径加载yaml得到为空
![image](https://github.com/user-attachments/assets/6a6829d9-19e0-48a0-934a-27a536d586fd)
因此我也尝试将其修改为
![image](https://github.com/user-attachments/assets/317486ac-2609-4441-bdc2-5099e1a0939a)，但仍提示
![image](https://github.com/user-attachments/assets/c50febdd-43fe-451c-a71a-016b25dd8b72)

**Comment by iorisa** [comment]
参考下面的配置，把`config2.yaml`文件放到`config/config2.yaml`或`~/.metagpt/config2.yaml`下:
```yaml
llm:
 api_type: "openai"
 model: "gpt-4o-mini"
 base_url: "http://oneapi.dev.deepwisdomai.com/v1"
 api_key: "sk-vUw9WeG***********************"
 temperature: 0.5

models:
 "gpt-3.5-turbo":  # <-- 这下面配个便宜点的模型
   api_type: "openai"
   model: "gpt-4o-mini"
   base_url: "http://oneapi.dev.deepwisdomai.com/v1"
   api_key: "sk-vUw9WeG***********************"
   temperature: 0.5

CALC_USAGE: True
```
其中：`gpt-3.5-turbo`那里可以配置一个便宜点的模型，如果没有配置个跟`llm`一样的模型也可以。
