### ISSUE TITLE
How to Use Third-Party Proxy with MetaGPT?

### ISSUE THREAD

**Issue by jingyaolliu** [geekan/MetaGPT#1685]
I have configured my parameters as follows:

```yaml
api_type: 'open_llm'  # or azure / ollama / open_llm etc. Check LLMType for more options
model: "gpt-4o-mini"  # or gpt-3.5-turbo-1106 / gpt-4-1106-preview
api_key: "sk-xxx"
base_url: "https://xiaoai.plus/v1"
```
Of course, I have also tried setting api_type to openai, but I keep encountering the following error:

`metagpt.utils.common:log_it:554 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 92.768(s), this was the 6th time calling it. exp: openai.types.completion_usage.CompletionUsage() argument after ** must be a mapping, not NoneType`

Is it possible that the issue arises from the use of a third-party proxy?
