### ISSUE TITLE
openai o1 raise BadRequestError: Unsupported parameter: 'max_tokens' is not supported with this model

### ISSUE THREAD

**Issue by iorisa** [geekan/MetaGPT#1709]
**Bug description**
```
openai.BadRequestError: Error code: 400 - {'error': {'message': "Unsupported parameter: 'max_tokens' is not supported with this model. Use 'max_completion_tokens' instead.", 'type': 'invalid_request_error', 'param': 'max_tokens', 'code': 'unsupported_parameter'}}
```

llm config:
```yaml
llm:
  api_type: "openai"  # or azure / ollama / groq etc.
  model: "o1"  # or gpt-3.5-turbo
  base_url: "https://api.openai.com/v1"  # or forward url / other llm url
  api_key:
```
