### ISSUE TITLE
如何去指定加载config文件？如何配置不同action的LLM配置？

### ISSUE THREAD

**Issue by moseshu** [geekan/MetaGPT#1737]
我想要去指定加载自己的config文件，不同的agent采用不同的模型配置？有没有相关的文档？metagpt --init-config 的方式非常不灵活，

**Comment by iorisa** [comment]
```python
class Action(SerializationMixin, ContextMixin, BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)

    name: str = ""
    i_context: Union[
        dict, CodingContext, CodeSummarizeContext, TestingContext, RunCodeContext, CodePlanAndChangeContext, str, None
    ] = ""
    prefix: str = ""  # aask*时会加上prefix，作为system_message
    desc: str = ""  # for skill manager
    node: ActionNode = Field(default=None, exclude=True)
    # The model name or API type of LLM of the `models` in the `config2.yaml`;
    #   Using `None` to use the `llm` configuration in the `config2.yaml`.
    llm_name_or_type: Optional[str] = None

    @model_validator(mode="after")
    @classmethod
    def _update_private_llm(cls, data: Any) -> Any:
        config = ModelsConfig.default().get(data.llm_name_or_type)
        if config:
            llm = create_llm_instance(config)
            llm.cost_manager = data.llm.cost_manager
            data.llm = llm
        return data
```
`Action`类提供了`llm_name_or_type`属性，可以从`config2.yaml`的`models`里加载对应的模型配置。
举个栗子：
`config2.yaml`的`models`配置如下：
```yaml
llm:
  api_type: "ollama"  # or azure / ollama / groq etc.
  model: "llama3.2"  # or gpt-3.5-turbo
  base_url: "http://localhost:11434/api"  # or forward url / other llm url
  api_key: "YOUR_API_KEYa"

models:
  "gpt35": # alias or model name
    api_type: "openai"  # or azure / ollama / groq etc.
    base_url: "YOUR_BASE_URL"
    api_key: "YOUR_API_KEY"
    proxy: "YOUR_PROXY"  # for LLM API requests
    model: "gpt-3.5-turbo"
    # timeout: 600 # Optional. If set to 0, default value is 300.
    # Details: https://azure.microsoft.com/en-us/pricing/details/cognitive-services/openai-service/
    pricing_plan: "" # Optional. Use for Azure LLM when its model name is not the same as OpenAI's
  "llama3.3": # alias or model name
    api_type: "ollama"  # or azure / ollama / groq etc.
    base_url: "YOUR_BASE_URL"
    api_key: "YOUR_API_KEY"
    proxy: "YOUR_PROXY"  # for LLM API requests
    # timeout: 600 # Optional. If set to 0, default value is 300.
    # Details: https://azure.microsoft.com/en-us/pricing/details/cognitive-services/openai-service/
    pricing_plan: "" # Optional. Use for Azure LLM when its model name is not the same as OpenAI's
```
