### ISSUE TITLE
setted "repair_llm_output: true" in  config2.yaml, but still meet the JSONDecodeError

### ISSUE THREAD

**Issue by huangcaiyun** [geekan/MetaGPT#934]
keeping meet the error，guys any idea would be helpful to resolve it.
有没有大佬能帮忙看看，谢谢~
i had setted "repair_llm_output:true" in configuration:

 ```
llm:
    api_type: "openai" 
    base_url: "http://127.0.0.1:8080/v1"
    api_key: "none"
    model: "chatglm2-6b"  
    repair_llm_output: true
```
but still meet parsing the JSON fail error:
![image](https://github.com/geekan/MetaGPT/assets/16162632/c5cb91f5-1ff6-42fe-8483-212887f697a6)

**Comment by time1527** [comment]
hello, my config2.yaml in v0.7.0:
```yaml
llm:
  api_type: 'zhipuai'
  api_key: 'xxxx'
  model: 'glm-3-turbo'
  base_url: 'https://open.bigmodel.cn/api/paas/v4/chat/completions'

repair_llm_output: true
```
JSONDecodeError appears one time, and/but it continues running.
