### ISSUE TITLE
Ollama运行报错

### ISSUE THREAD

**Issue by bobwong89757** [geekan/MetaGPT#976]
**Bug description**

<img width="930" alt="image" src="https://github.com/geekan/MetaGPT/assets/6356061/438d2af6-1c44-4957-84c4-74b99f6ca9aa">

**Bug solved method**

**Environment information**

- LLM type and model name: Ollama, llama2
- System version: mac os 13.1
- Python version: 3.11.8

```
# Full Example: https://github.com/geekan/MetaGPT/blob/main/config/config2.example.yaml
# Reflected Code: https://github.com/geekan/MetaGPT/blob/main/metagpt/config2.py
llm:
  api_type: ollama
  base_url: 'http://127.0.0.1:11434/api'
  model: 'llama2'

```
